web/ctfplt/accounts/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views, form

app_name = "accounts"
urlpatterns = [
    url(r'^$', views.profile, name="index"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^update/$', views.update, name="update"),
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html', 'authentication_form': form.LoginForm}, name="login"), 
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login'}, name="logout"),  
    #url(r'^admin/addusers/$', auth_views.logout, {'next_page': '/accounts/login'}, name="logout"),  
]

web/ctfplt/ctfplt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include("scoreboard.urls")),
    url(r"^problems/", include("problems.urls")),
    url(r"^accounts/", include("accounts.urls")),
    url(r"^scoreboard/", include("scoreboard.urls")),
    url(r"^guides/", include("guides.urls")),
    url(r'^markdownx/', include('markdownx.urls')),
]

web/ctfplt/guides/urls.py
from django.conf.urls import include, url
from . import views

app_name = "guides"
urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^(?P<articleTitle>[\w\s]+)/$", views.detail, name="detail"),
]

web/ctfplt/problems/urls.py
from django.conf.urls import include, url
from . import views

app_name = "problems"
urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^(?P<problemTitle>[\w\s]+)/$", views.detail, name="detail"),
    url(r"^(?P<problemTitle>[\w\s]+)/unlockhint/$", views.unlockHint, name="unlockHint"),
    url(r"^(?P<problemTitle>[\w\s]+)/submit/$", views.submit, name="submit"),
]

web/ctfplt/scoreboard/urls.py
from django.conf.urls import include, url
from . import views

app_name = "scoreboard"
urlpatterns = [
    url(r"^$", views.statistics, name="index"),
    url(r"^graphData/$", views.graphData, name="graphData"),
    url(r"^allUsers/$", views.allUsers, name="allUsers"),
]

web/ctfplt/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title>CTF Platform</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/zabuto_calendar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/gritter/css/jquery.gritter.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'lineicons/style.css' %}">    
    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
    <script src="{% static 'js/chart-master/Chart.js' %}"></script>

    <link href="{% static '/markdownx/admin/css/markdownx.css' %}" type="text/css" media="all" rel="stylesheet" />
  </head>

  <body>

    <section id="container" >
      <!-- TOP BAR CONTENT & NOTIFICATIONS -->
      <!--header start-->
      <header class="header black-bg">
        <div class="sidebar-toggle-box">
          <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
        </div>
        <!--logo start-->
	<a href="/" class="logo">
	  <b>CTF Platform</b>
	</a>
        <!--logo end-->
        <div class="top-menu">
          <ul class="nav pull-right top-menu">
	    {% if request.user.is_authenticated %}
            <li><a class="logout" href="{% url 'accounts:logout' %}">Logout</a></li>
	    {% else %}
            <li><a class="login" href="{% url 'accounts:login' %}">Login</a></li>
	    {% endif %}
          </ul>
        </div>
      </header>
      <!--header end-->
      
      <!-- MAIN SIDEBAR MENU -->
      <!--sidebar start-->
      <aside>
        <div id="sidebar"  class="nav-collapse" style="z-index: 1;">
          <!-- sidebar menu start-->
          <ul class="sidebar-menu" id="nav-accordion">
            <h5 class="centered">
	      {% if request.user.is_authenticated %}
	      Welcome {{ request.user.username }}!!
	      {% else %}
	      &nbsp;
	      {% endif %}
	    </h5>
            <li class="sub-menu">
              <a {% block navScoreboard %}{% endblock %} href="{% url 'scoreboard:index' %}">
		<i class="fa fa-line-chart"></i>
                <span>Scoreboard</span>
              </a>
            </li>
            <li class="sub-menu">
              <a {% block navAccounts %}{% endblock %} href="{% url 'accounts:index' %}">
		<i class="fa fa-address-card"></i>
                <span>Account</span>
              </a>
            </li>
            <li class="sub-menu">
              <a {% block navProblems %}{% endblock %} href="{% url 'problems:index' %}">
		<i class="fa fa-flag"></i>
                <span>Problems</span>
              </a>
            </li>
            <li class="sub-menu">
              <a {% block navShell %}{% endblock %} href="">
		<i class="fa fa-terminal"></i>
                <span>Terminal</span>
              </a>
            </li>
            <li class="sub-menu">
              <a {% block navGuides %}{% endblock %} href="{% url 'guides:index' %}">
		<i class="fa fa-graduation-cap"></i>
                <span>Guides</span>
              </a>
            </li>
          </ul>
          <!-- sidebar menu end-->
        </div>
      </aside>
      <!--sidebar end-->

      <!-- MAIN CONTENT -->
      <!--main content start-->
      <section id="main-content">
        <section class="wrapper">
          <div class="row">
	    {% block mainContents %}
	    {% endblock %}
	    {% block rightContents %}
	    {% endblock %}
	  </div><!--/row -->
        </section>
      </section>

      <!--main content end-->
      <!--footer start
      <footer class="site-footer">
	<div class="text-center">
	  Designed by Alvarez.is
	</div>
      </footer>
      footer end-->
    </section>


    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script class="include" type="text/javascript" src="{% static 'js/jquery.dcjqaccordion.2.7.js' %}"></script>
    <!--
    <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.js' %}" type="text/javascript"></script>
    -->
    <script src="{% static 'js/jquery.sparkline.js' %}"></script>


    <!--common script for all pages-->
    <script src="{% static 'js/common-scripts.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/gritter/js/jquery.gritter.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/gritter-conf.js' %}"></script>

    <!--script for this page-->
    <script src="{% static 'js/sparkline-chart.js' %}"></script>    
    <script src="{% static 'js/chart-master/Chart.js' %}"></script>

    {% block javascript %}
    {% endblock %}
  </body>
</html>