web/ctfplt/accounts/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views, form

app_name = "accounts"
urlpatterns = [
    url(r'^$', views.profile, name="index"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^update/$', views.update, name="update"),
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html', 'authentication_form': form.LoginForm}, name="login"), 
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login'}, name="logout"),  
    #url(r'^admin/addusers/$', auth_views.logout, {'next_page': '/accounts/login'}, name="logout"),  
]

web/ctfplt/ctfplt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include("scoreboard.urls")),
    url(r"^problems/", include("problems.urls")),
    url(r"^accounts/", include("accounts.urls")),
    url(r"^scoreboard/", include("scoreboard.urls")),
    url(r"^guides/", include("guides.urls")),
    url(r'^markdownx/', include('markdownx.urls')),
]

web/ctfplt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from problems.models import Problem
from django.utils import timezone

class Affiliate(models.Model):
    name = models.CharField(max_length=64, default="")
    solvedProblems = models.ManyToManyField(Problem, blank=True)
    score = models.IntegerField(default = 0)
    def __str__(self):
        return self.name

class User(AbstractUser):
    userID = models.IntegerField(default = 0)
    affiliate = models.ForeignKey(Affiliate, on_delete=models.CASCADE, default=None, blank=True, null=True)
    score = models.IntegerField(default = 0)
    lastSubmitDatetime = models.DateTimeField(default=timezone.now)

    solvedProblems = models.ManyToManyField(Problem, blank=True, related_name="solvedProblems")
    noHintSolvedProblems = models.ManyToManyField(Problem, blank=True, related_name="noHintSolvedProblems")
    hintedProblems = models.ManyToManyField(Problem, blank=True, related_name="hintedProblems")
    availableProblems = models.ManyToManyField(Problem, blank=True, related_name="availableProblems")

    def addSolvedProblems(self, problem):
        self.solvedProblems.add(problem)
        self.save()
    def addNoHintedSolvedProblems(self, problem):
        self.noHintSolvedProblems.add(problem)
        self.save()
    def addHintedProblems(self, problem):
        self.hintedProblems.add(problem)
        self.save()
    def addAvailableProblems(self, problems):
        for problem in problems:
            self.availableProblems.add(problem)
        self.save()

class SubmittedHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, blank=True, null=True)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE, default=None, blank=True, null=True)
    isCorrect = models.BooleanField(default = False)
    withHint = models.BooleanField(default = False)
    submitDatetime = models.DateTimeField(default=timezone.now)
    def __str__(self):
        ret = self.user.username + "(" + self.problem.title + "): "
        if self.isCorrect:
            ret += "Correct"
        else:
            ret += "Wrong"
        if self.withHint:
            ret += ", with the hint"
        return ret

web/ctfplt/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import User
from accounts.models import SubmittedHistory

@login_required(login_url="/accounts/login/")
def profile(request):
    topUsers = User.objects.filter(is_superuser__exact=False).order_by("-score", "lastSubmitDatetime")
    idx = 1
    for user in topUsers:
        if user.username == request.user.username:
            break
        idx += 1
    maxSize = User.objects.filter(is_superuser__exact=False).count()
    fromIdx = 0 if idx-3 < 0 else idx-3
    toIdx   =  maxSize if idx+3 > maxSize else idx+3
    aroundUsers = topUsers[fromIdx:toIdx]
    history = SubmittedHistory.objects.filter(user__exact=request.user).order_by("-submitDatetime")[:5]
    return render(request,"accounts/profile.html", 
                  {'user' : request.user,
                   'baseIdx': fromIdx, 
                   'idx': idx,
                   'aroundUsers': aroundUsers,
                   'history': history
               }
              )

@login_required(login_url="/accounts/login/")
def update(request):
    #newUserID = request.POST['userID']
    newUsername = request.POST['userName']
    #newAffiliate = request.POST['affiliate']
    newEmail = request.POST['email']
    newPW = request.POST['newPW']
    confirmPW = request.POST['confirmPW']
    currentPW = request.POST['currentPW']
    #return render(request, 'accounts/error.html')

    changePWFlag = True
    if newPW == "" or (newPW != confirmPW):
        changePWFlag = False
    if request.user.check_password(currentPW) and changePWFlag:
        request.user.username = newUsername
        if newPW != "":
            request.user.set_password(newPW)
        request.user.save()
        return HttpResponseRedirect(reverse('accounts:index'))
    else:
        return render(request,"accounts/profile.html", 
                      {'user' : request.user, 
                       "errorStr": "Update Failed. Please try again.",
                   }
                  )

web/ctfplt/accounts/templates/accounts/base.html
{% extends 'base.html' %}
{% block navAccounts %}class="active"{% endblock %}

web/ctfplt/accounts/templates/accounts/error.html
error

web/ctfplt/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block mainContents %}
<!-- center -->
<div class="col-lg-12 main-chart">
  <div class="row">
    <div class="col-md-12 mb">
      <form method="post" class="form-login" action="{% url 'accounts:login' %}">
	{% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
	<h2 class="form-login-heading">sign in now</h2>
	<div class="login-wrap">
	  <input type="text" name="{{ form.username.name }}" class="form-control" placeholder="User ID" autofocus>
	  <br>
	  <input type="password" name="{{ form.password.name }}"  class="form-control" placeholder="Password">
	  &nbsp;
	  <button class="btn btn-theme btn-block" value="login" type="submit"><i class="fa fa-lock"></i> SIGN IN</button>
	  {% if form.errors %}
	  <hr>
	  <p>Your username and password didn't match. Please try again.</p>
	  {% endif %}
	</div>
      </form>	  	
    </div>
  </div>
</div>
{% endblock %}

web/ctfplt/accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}

{% block javascript %}
{% endblock %}

{% block mainContents %}
<div class="col-lg-12">
  <div class="form-panel">
    <h4 class="mb"><i class="fa fa-angle-right"></i> Your Rank</h4>
    <table class="table table-striped table-advance table-hover">
      <thead>
	<tr>
	  <th width="5%"><i class="fa fa-line-chart "></i></th>
	  <th width="10%"><i class="fa fa-trophy"></i> Score</th>
	  <th width="20%"><i class="fa fa-user"></i> User</th>
	  <th width="20%"><i class="fa fa-users"></i> Affiliate</th>
	  <th width="10%"><i class="fa fa-lightbulb-o"></i> No Hint</th>
	</tr>
      </thead>
      <tbody>
	{% for iterUser in aroundUsers %}
	{% if user == iterUser %}
	<tr class="bg-info">
	  <td style="background-color:transparent;">{{ forloop.counter| add:baseIdx }}</td>
	  <td style="background-color:transparent;">{{ iterUser.score }}</td>
	  <td style="background-color:transparent;">{{ iterUser.username }}</td>
	  <td style="background-color:transparent;">{{ iterUser.affiliate }}</td>
	  <td style="background-color:transparent;">{{ iterUser.noHintSolvedProblems.all | length }}</td>
	</tr>
	{% else %}
	<tr>
	  <td>{{ forloop.counter| add:baseIdx}}</td>
	  <td>{{ iterUser.score }}</td>
	  <td>{{ iterUser.username }}</td>
	  <td>{{ iterUser.affiliate }}</td>
	  <td>{{ iterUser.noHintSolvedProblems | length }}</td>
	</tr>
	{% endif %}
	{% endfor %}
      </tbody>
    </table>
    <hr>
    <h4 class="mb"><i class="fa fa-angle-right"></i> Activity</h4>
    <table class="table table-striped table-advance table-hover">
      <thead>
	<tr>
	  <th width="10%"><i class="fa fa-clock-o"></i> Submit Date</th>
	  <th width="10%"><i class="fa fa-flag"></i> Problem</th>
	  <th width="30%"><i class="fa fa-trophy"></i> Correct?</th>
	</tr>
      </thead>
      <tbody>
	{% for record in history %}
	<tr>
	  <td>{{ record.submitDatetime }}</td>
	  <td>{{ record.problem.title }}</td>
	  <td>{% if record.isCorrect %}Correct!!{% else %}Wrong...{% endif %}</td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
  </div>

  <div class="form-panel">
    <h4 class="mb"><i class="fa fa-angle-right"></i> Profile</h4>
    {% if errorStr %}
    <p>{{ errorStr }}</p>
    {% endif %}
    <hr>
    <form class="form-horizontal style-form" method="post" action="{% url 'accounts:update' %}">
      {% csrf_token %}
      <div class="form-group">
        <label class="col-sm-2 col-sm-2 control-label">UserID</label>
        <div class="col-sm-10">
	  <input class="form-control" type="text" name="userID" placeholder="{{ user.userID }}" disabled>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 col-sm-2 control-label">Username</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" name="userName" value="{{ user.username }}">
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 col-sm-2 control-label">Affiliate</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" name="affiliate" value="{{ user.affiliate }}" disabled>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-2 col-sm-2 control-label">Mail Address</label>
        <div class="col-lg-10">
          <input type="text" class="form-control" name="email" value="{{ user.email }}">
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 col-sm-2 control-label">Change Password</label>
        <div class="col-sm-10">
          <input type="password"  class="form-control" name="newPW" placeholder="New Password">
	  &nbsp;
          <input type="password"  class="form-control" name="confirmPW" placeholder="Confirm">
        </div>
      </div>
      <hr>
        <label class="col-sm-2 col-sm-2 control-label">Current Password</label>
        <div class="col-sm-10">
          <input type="password" {% if errorStr %}id="focusedInput"{% endif %} class="form-control" name="currentPW" placeholder="">
        </div>
	&nbsp;
	<button class="btn btn-theme btn-block" type="submit"><i class="fa fa-hand-o-up"></i> Submit</button>
    </form>
  </div>
</div><!-- col-lg-12-->      	
{% endblock %}

{% block rightContents %}
{% endblock %}