web/ctfplt/ctfplt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include("scoreboard.urls")),
    url(r"^problems/", include("problems.urls")),
    url(r"^accounts/", include("accounts.urls")),
    url(r"^scoreboard/", include("scoreboard.urls")),
    url(r"^guides/", include("guides.urls")),
    url(r'^markdownx/', include('markdownx.urls')),
]

web/ctfplt/problems/urls.py
from django.conf.urls import include, url
from . import views

app_name = "problems"
urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^(?P<problemTitle>[\w\s]+)/$", views.detail, name="detail"),
    url(r"^(?P<problemTitle>[\w\s]+)/unlockhint/$", views.unlockHint, name="unlockHint"),
    url(r"^(?P<problemTitle>[\w\s]+)/submit/$", views.submit, name="submit"),
]

web/ctfplt/problems/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

class Tag(models.Model):
    name = models.CharField(max_length=16, default="")
    def __str__(self):
        return self.name

class Problem(models.Model):
    title = models.CharField(max_length=128, default="")
    flag = models.CharField(max_length=64, default="")
    tags = models.ManyToManyField(Tag, blank=True)
    score = models.IntegerField(default = 0)
    unlockProblems = models.ManyToManyField("self", blank=True)
    _description = MarkdownxField(default="")
    _hint = MarkdownxField(default="")
    def __str__(self):
        return self.title

    @property
    def description(self):
        return markdownify(self._description)
    @property
    def hint(self):
        return markdownify(self._hint)

web/ctfplt/problems/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import Problem
from accounts.models import SubmittedHistory
from datetime import datetime 

@login_required(login_url="/accounts/login/")
def index(request):
    return render(request, "problems/index.html",
                  {'user' : request.user, }
              )

@login_required(login_url="/accounts/login/")
def detail(request, problemTitle):
    problem = get_object_or_404(Problem, title=problemTitle)
    if problem not in request.user.availableProblems.all():
        return HttpResponseRedirect(reverse('problems:index'))
    showModalFlag = 0
    if ("showModalFlag" in request.COOKIES) and (request.COOKIES["showModalFlag"] == "correct"):
        showModalFlag = 1
    if ("showModalFlag" in request.COOKIES) and (request.COOKIES["showModalFlag"] == "fail"):
        showModalFlag = 2
    response = render(request, "problems/detail.html",
                      {'user': request.user,
                       "problem": problem,
                       "showModalFlag": showModalFlag}
                  )
    response.delete_cookie('showModalFlag')
    return response


@login_required(login_url="/accounts/login/")
def unlockHint(request, problemTitle):
    problem = get_object_or_404(Problem, title=problemTitle)
    if problem not in request.user.hintedProblems.all():
        request.user.addHintedProblems(problem)
    return HttpResponseRedirect(reverse('problems:detail',
                                        kwargs={'problemTitle':problemTitle}))

@login_required(login_url="/accounts/login/")
def submit(request, problemTitle):
    problem = get_object_or_404(Problem, title=problemTitle)
    response = HttpResponseRedirect(reverse('problems:detail',
                                            kwargs={'problemTitle':problemTitle}))
    if (problem in request.user.availableProblems.all()) and (problem not in request.user.solvedProblems.all()):
        withHint = True
        if problem not in request.user.hintedProblems.all():
            withHint = False
        if problem.flag == request.POST['flag']:
            request.user.addSolvedProblems(problem)
            request.user.lastSubmitDatetime = datetime.now()
            if not withHint:
                request.user.addNoHintedSolvedProblems(problem)
            request.user.score = request.user.score + problem.score
            request.user.addAvailableProblems(problem.unlockProblems.all())
            request.user.save()

            if problem not in request.user.affiliate.solvedProblems.all():
                request.user.affiliate.score = request.user.affiliate.score + problem.score
                request.user.affiliate.solvedProblems.add(problem)
                request.user.affiliate.save()
            response.set_cookie("showModalFlag", "correct")
            isCorrect = True
        else:
            response.set_cookie("showModalFlag", "fail")
            isCorrect = False
        history = SubmittedHistory(user = request.user, withHint = withHint, isCorrect = isCorrect, problem=problem)
        history.save()
    return response

web/ctfplt/problems/templates/problems/base.html
{% extends 'base.html' %}
{% block navProblems %}class="active"{% endblock %}

web/ctfplt/problems/templates/problems/detail.html
{% extends 'problems/base.html' %}

{% block mainContents %}
<div class="col-lg-12">
  <div class="form-panel">
    <h4><i class="fa fa-angle-right"></i> {{ problem.title }} [{{ problem.score }}pt]{% if problem in user.getSolvedProblems %} <i class="fa fa-flag"></i>{% endif %}</h4>
    <hr>
    <div class="form-panel-content">
      {{ problem.description | safe}}
    </div>

    {% if problem in user.solvedProblems.all %}
    <form class="form-inline" role="form" method="post" action="{% url 'problems:submit' problem %}">
      {% csrf_token %}
      <div style="text-align: center;">
      <input type="text" class="form-control" style="width:500px;" name="flag" placeholder="You have already pwned this problem." disabled>
      <button type="submit" class="btn btn-theme" disabled>Submit</button>
      </div>
    </form>
    {% else %}
    <form class="form-inline" role="form" method="post" action="{% url 'problems:submit' problem %}">
      {% csrf_token %}
      <div style="text-align: center;">
      <input type="text" class="form-control" style="width:500px;" name="flag" placeholder="Click here to enter the Flag!!">
      <button type="submit" class="btn btn-theme">Submit</button>
      </div>
    </form>
    {% endif %}
    <hr>
    <form method="post" action="{% url 'problems:unlockHint' problem %}">
      {% csrf_token %}
      {% if problem in user.hintedProblems.all %}
      <button type="button" class="btn btn-primary btn-xs" disabled>Gimme a Hint!!</button>
      <div class="form-panel-content">
	{{ problem.hint | safe}}
      </div>
      {% else %}
      <button type="submit" class="btn btn-primary btn-xs">Gimme a Hint!!</button>
      {% endif %}
    </form>
  </div>
</div><!-- /col-md-12 -->
{% endblock %}

{% block rightContents %}
{% endblock %}

{% block javascript %}

{% if problem in user.solvedProblems.all and showModalFlag == 1 %}
<div class="modal fade" id="correctModal" tabindex="-1" role="dialog" aria-labelledby="collectModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title" id="collectModalLabel">Correct!!</h4>
      </div>
      <div class="modal-body">
	Congratulations! You earned {{ problem.score }} points!!
      </div>
      <div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>      				
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('.modal').modal('show');
    });
</script>
{% endif %}

{% if showModalFlag == 2 %}
<div class="modal fade" id="correctModal" tabindex="-1" role="dialog" aria-labelledby="collectModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title" id="collectModalLabel">Failed!!</h4>
      </div>
      <div class="modal-body">
	Please try again..
      </div>
      <div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>      				
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('.modal').modal('show');
    });
</script>
{% endif %}


{% endblock %}

web/ctfplt/problems/templates/problems/index.html
{% extends 'problems/base.html' %}

{% block mainContents %}
<div class="col-lg-12">
  <div class="form-panel">
    <table class="table table-striped table-advance table-hover">
      <h4><i class="fa fa-angle-right"></i> Problems</h4>
      <hr>
      <thead>
	<tr>
	  <th width="5%"><i class="fa fa-flag"></i></th>
	  <th width="30%"><i class="fa fa-puzzle-piece"></i> Problem</th>
	  <th width="15%"><i class="fa fa-trophy"></i> Score</th>
	  <th width="50%"><i class="fa fa-tags"></i> Tags</th>
	</tr>
      </thead>
      <tbody>

	{% for problem in user.availableProblems.all %}
	<tr>
	  <td>{% if problem in user.solvedProblems.all %}<i class="fa fa-check"></i>{% endif %}</td>
	  <td><a href="{% url 'problems:detail' problem %}">{{ problem.title }}</a></td>
	  <td>{{ problem.score }}</td>
	  <td>
	    {% for tag in problem.tags.all %}
	    {% if tag.name == "web" %}
	    <span class="label label-primary">{{ tag }}</span>
	    {% elif tag.name == "binary" %}
	    <span class="label label-info">{{ tag }}</span>
	    {% elif tag.name == "network" %}
	    <span class="label label-warning">{{ tag }}</span>
	    {% elif tag.name == "misc" %}
	    <span class="label label-default">{{ tag }}</span>
	    {% elif tag.name == "hard" %}
	    <span class="label label-danger">{{ tag }}</span>
	    {% elif tag.name == "easy" %}
	    <span class="label label-success">{{ tag }}</span>
	    {% endif %}
	    {% endfor %}
	  </td>
	</tr>
	{% endfor %}

      </tbody>
    </table>
  </div><!-- /content-panel -->
</div><!-- /col-md-12 -->
{% endblock %}

{% block rightContents %}
{% endblock %}