web/ctfplt/ctfplt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include("scoreboard.urls")),
    url(r"^problems/", include("problems.urls")),
    url(r"^accounts/", include("accounts.urls")),
    url(r"^scoreboard/", include("scoreboard.urls")),
    url(r"^guides/", include("guides.urls")),
    url(r'^markdownx/', include('markdownx.urls')),
]

web/ctfplt/scoreboard/urls.py
from django.conf.urls import include, url
from . import views

app_name = "scoreboard"
urlpatterns = [
    url(r"^$", views.statistics, name="index"),
    url(r"^graphData/$", views.graphData, name="graphData"),
    url(r"^allUsers/$", views.allUsers, name="allUsers"),
]

web/ctfplt/scoreboard/models.py
from django.db import models
from problems.models import Problem
from accounts.models import User

class PostedHistory(models.Model):
    postedDateTime = models.DateTimeField()
    postedUser = models.ForeignKey(User)
    postedProblem = models.ForeignKey(Problem)
    result = models.BooleanField()

web/ctfplt/scoreboard/views.py
from django.shortcuts import render
from accounts.models import User, SubmittedHistory
from django.http.response import JsonResponse
from accounts.models import Affiliate

def statistics(request):
    topUsers = User.objects.filter(is_superuser__exact=False).order_by("-score", "lastSubmitDatetime")[:5]
    history = SubmittedHistory.objects.filter(isCorrect__exact=True).order_by("-submitDatetime")[:10]
    return render(request,"scoreboard/statistics.html",
                  {"topUsers": topUsers, 
                   "history": history}
              )

def allUsers(request):
    allUsers = User.objects.filter(is_superuser__exact=False).order_by("-score", "lastSubmitDatetime")
    history = SubmittedHistory.objects.filter(isCorrect__exact=True).order_by("-submitDatetime")[:10]
    return render(request,"scoreboard/allUsers.html",
                  {"allUsers": allUsers, 
                   "history": history}
              )

def graphData(request):
    labels = []
    datum = {}
    datum["fillColor"]   = "rgba(151,187,205,0.5)"
    datum["strokeColor"] = "rgba(151,187,205,1)"
    datum["data"] = []
    for affiliate in Affiliate.objects.all().order_by("name"):
        labels += [affiliate.name]
        datum["data"] += [affiliate.score]
        datasets = [datum]
    return JsonResponse({"labels": labels, "datasets": datasets})

web/ctfplt/scoreboard/templates/scoreboard/allUsers.html
{% extends 'scoreboard/base.html' %}

{% block mainContents %}
<div class="col-lg-9">
  <div class="form-panel">
    <h4 class="mb"><i class="fa fa-angle-right"></i> All Users</h4>
    <hr>
    <table class="table table-striped table-advance table-hover">
      <thead>
	<tr>
	  <th width="5%"><i class="fa fa-line-chart "></i></th>
	  <th width="10%"><i class="fa fa-trophy"></i> Score</th>
	  <th width="20%"><i class="fa fa-user"></i> User</th>
	  <th width="20%"><i class="fa fa-users"></i> Affiliate</th>
	  <th width="10%"><i class="fa fa-lightbulb-o"></i> No Hint</th>
	</tr>
      </thead>
      <tbody>
	{% for user in allUsers %}
	<tr>
	  <td>{{ forloop.counter }}</td>
	  <td>{{ user.score }}</td>
	  <td>{{ user.username }}</td>
	  <td>{{ user.affiliate }}</td>
	  <td>{{ user.noHintSolvedProblems | length }}</td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
  </div>
</div><!-- col-lg-12-->      	
{% endblock %}

{% block rightContents %}
<div class="col-lg-3 ds">
  <h3>Recent Submission</h3>
  {% for record in history %}
  <div class="desc">
    <div class="thumb">
      <span class="badge bg-theme"><i class="fa fa-clock-o"></i></span>
    </div>
    <div class="details">
      <p><muted>{{ record.submitDatetime }}</muted><br/>
	{{ record.user.username }} won "{{ record.problem.title}}" {% if record.withHint %}.{% else %}without the hint !!{% endif %}	
      </p>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

{% block javascript %}
{% endblock %}

web/ctfplt/scoreboard/templates/scoreboard/base.html
{% extends 'base.html' %}
{% block navScoreboard %}class="active"{% endblock %}

web/ctfplt/scoreboard/templates/scoreboard/statistics.html
{% extends 'scoreboard/base.html' %}

{% block mainContents %}
<div class="col-lg-9">
  <div class="form-panel">
    <h4 class="mb"><i class="fa fa-angle-right"></i> Top5 Users</h4>
    <hr>
    <table class="table table-striped table-advance table-hover">
      <thead>
	<tr>
	  <th width="5%"><i class="fa fa-line-chart "></i></th>
	  <th width="10%"><i class="fa fa-trophy"></i> Score</th>
	  <th width="20%"><i class="fa fa-user"></i> User</th>
	  <th width="20%"><i class="fa fa-users"></i> Affiliate</th>
	  <th width="10%"><i class="fa fa-lightbulb-o"></i> No Hint</th>
	</tr>
      </thead>
      <tbody>
	{% for user in topUsers %}
	<tr>
	  <td>{{ forloop.counter }}</td>
	  <td>{{ user.score }}</td>
	  <td>{{ user.username }}</td>
	  <td>{{ user.affiliate }}</td>
	  <td>{{ user.noHintSolvedProblems.all | length }}</td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
    <a href="{% url 'scoreboard:allUsers' %}"><button type="button" class="btn btn-info">All Users</button></a>
  </div>

  <div class="form-panel">
    <h4 class="mb"><i class="fa fa-angle-right"></i> Statistics</h4>
    <hr>
    <div class="panel-body text-center" id="barContainer">
      <canvas id="bar"></canvas>
    </div>
  </div>
</div><!-- col-lg-12-->      	
{% endblock %}

{% block rightContents %}
<div class="col-lg-3 ds">
  <h3>Recent Submission</h3>
  {% for record in history %}
  <div class="desc">
    <div class="thumb">
      <span class="badge bg-theme"><i class="fa fa-clock-o"></i></span>
    </div>
    <div class="details">
      <p><muted>{{ record.submitDatetime }}</muted><br/>
	{{ record.user.username }} won "{{ record.problem.title}}" {% if record.withHint %}.{% else %}without the hint !!{% endif %}	
      </p>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

{% block javascript %}
<script>
  $.getJSON("{% url 'scoreboard:graphData' %}", function ( barChartData ){
  var ctx = document.getElementById("bar").getContext("2d");
  ctx.canvas.width = $("#barContainer").width();
  ctx.canvas.height = Math.max($("#barContainer").height(), 320);
  new Chart(ctx).Bar(barChartData);
  });
</script>
{% endblock %}